server:
  port: 8081
dubbo:
  application:
    name: shop_service-impl
  registry:
    protocol: zookeeper
    port: 2181
    address: 192.168.140.128
mybatis:
  type-aliases-package: com.qf.entity
  mapper-locations: classpath*:com/qf/dao/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql:///shop_1804
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    type: com.mchange.v2.c3p0.ComboPooledDataSource
