server:
  port: 8086
spring:
  redis:
    host: 192.168.140.128
    password: root
dubbo:
  application:
    name: shop_car
  registry:
    address: 192.168.140.128
    port: 2181
    protocol: zookeeper
  consumer:
    check: false
    timeout: 1500